#!/usr/bin/sh
# do prime-run "command run" when in integrated graphics mode to run the one command on the nvidia gpu

# when using iGPU with PRIME render offloading, 'prime-run <cmd>' will use dGPU 

__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"

